name: Multivar

on:
  workflow_call:
    inputs:
      var_0:
        required: false
        type: string
      var_1:
        required: false
        type: string

jobs:
  echo-vars:
    name: Echo vars
    runs-on: ubuntu-latest

    steps:
      - name: Create short sha
        run: |
          for i in $(seq 1 2); do
            echo "${{ inputs.var_$i }}
          done
